# Generated by Django 2.1.1 on 2018-10-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='protfolio',
            new_name='portfolio',
        ),
    ]
